[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3.11 -m pip install -r OtoYedekParca_App/requirements.txt"]

[start]
cmd = "cd OtoYedekParca_App && gunicorn app:app --bind 0.0.0.0:$PORT"
